const SPOTIFY_API_URL = "https://api.spotify.com/v1";

export const useSpotify = (token: string | null) => {
  const searchTrackURI = async (trackName: string, artistName: string) => {
    if (!token) {
      console.error("❌ Missing Spotify Token!");
      return null;
    }

    try {
      const response = await fetch(
        `${SPOTIFY_API_URL}/search?q=track:${encodeURIComponent(trackName)}+artist:${encodeURIComponent(
          artistName
        )}&type=track&limit=1`,
        {
          headers: { Authorization: `Bearer ${token}` },
        }
      );

      if (!response.ok) {
        throw new Error(`❌ Spotify search failed: ${await response.text()}`);
      }

      const data = await response.json();
      return data.tracks.items[0]?.uri || null; // Return track URI if found
    } catch (error) {
      console.error("❌ Error searching for track:", error);
      return null;
    }
  };

  const createSpotifyPlaylist = async (playlistName: string, trackURIs: string[]) => {
    if (!token) {
      console.error("❌ Missing Spotify Token!");
      return null;
    }

    try {
      // Step 1: Create an empty playlist
      const createPlaylistResponse = await fetch(`${SPOTIFY_API_URL}/me/playlists`, {
        method: "POST",
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          name: playlistName,
          description: "Generated by YouLists AI",
          public: false,
        }),
      });

      if (!createPlaylistResponse.ok) {
        throw new Error(`❌ Failed to create playlist: ${await createPlaylistResponse.text()}`);
      }

      const playlistData = await createPlaylistResponse.json();
      const playlistId = playlistData.id;

      // Step 2: Add songs to the playlist
      if (trackURIs.length > 0) {
        await fetch(`${SPOTIFY_API_URL}/playlists/${playlistId}/tracks`, {
          method: "POST",
          headers: {
            Authorization: `Bearer ${token}`,
            "Content-Type": "application/json",
          },
          body: JSON.stringify({ uris: trackURIs }),
        });
      }

      console.log("✅ Playlist created successfully:", playlistData);
      return playlistData.external_urls.spotify; // Return Spotify playlist link
    } catch (error) {
      console.error("❌ Error creating Spotify playlist:", error);
      return null;
    }
  };

  return { searchTrackURI, createSpotifyPlaylist };
};
