import React, { useState, useEffect, useMemo, useCallback } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { ArrowLeft, Save, ExternalLink, Sun, Moon, RefreshCw, Download } from "lucide-react";
import { usePlaylistContext, Song } from "../context/PlaylistContext";
import { usePlaylistHistory } from "../actions/usePlaylistHistory";
import { useSpotify } from "../actions/useSpotify";
import { useTheme } from "../context/ThemeContext";
import { ProcessedImage } from "../utils/imageUtils";
import UniversalExport from "./UniversalExport";

interface EnhancedSong extends Song {
  coverUrl?: string;
  previewUrl?: string;
  popularity?: number;
  duration_ms?: number;
}

const PlaylistPage: React.FC = () => {
  const navigate = useNavigate();
  const location = useLocation();
  const { theme, toggleTheme } = useTheme();
  const { playlistName, currentPlaylist, tags, lastPrompt, advancedParameters, songCount, selectedImage } = usePlaylistContext();
  const { savePlaylist } = usePlaylistHistory();
  const token = localStorage.getItem("spotify_token");
  const isGuestMode = localStorage.getItem("guest_mode") === "true";
  const { searchTrackURI, getTrackDetails, createSpotifyPlaylist } =
    useSpotify(token);

  const playlist = useMemo(() => {
    const playlistData = location.state?.playlistData || {
      playlist: currentPlaylist,
    };
    return Array.isArray(playlistData?.playlist) ? playlistData.playlist : [];
  }, [location.state, currentPlaylist]);

  const coverImage = useMemo(() => {
    return location.state?.coverImage as ProcessedImage | null;
  }, [location.state]);

  const [isExporting, setIsExporting] = useState(false);
  const [exportProgress, setExportProgress] = useState(0);
  const [exportedPlaylistURL, setExportedPlaylistURL] = useState<string | null>(
    null
  );
  const [savedToHistory, setSavedToHistory] = useState(false);
  const [customPlaylistName, setCustomPlaylistName] = useState(
    playlistName || "ai-generated playlist"
  );
  const [enhancedPlaylist, setEnhancedPlaylist] = useState<EnhancedSong[]>([]);
  const [isEnhancing, setIsEnhancing] = useState(false);

  useEffect(() => {
    const loadAlbumCovers = async () => {
      if (playlist.length > 0 && token && !isGuestMode) {
        setIsEnhancing(true);
        try {
          const enhanced = await Promise.all(
            playlist.map(async (song: Song) => {
              try {
                const uri = await searchTrackURI(song.title, song.artist);
                if (uri) {
                  const details = await getTrackDetails(uri);
                  return {
                    ...song,
                    uri,
                    coverUrl: details?.album.images[0]?.url,
                    previewUrl: details?.preview_url,
                    popularity: details?.popularity,
                    duration_ms: (details as any)?.duration_ms,
                  };
                }
                return { ...song };
              } catch (e) {
                return { ...song };
              }
            })
          );
          setEnhancedPlaylist(enhanced);
        } catch (error) {
          console.error("Error enhancing playlist:", error);
          setEnhancedPlaylist(playlist.map((song: Song) => ({ ...song })));
        } finally {
          setIsEnhancing(false);
        }
      } else {
        setEnhancedPlaylist(playlist.map((song: Song) => ({ ...song })));
      }
    };

    loadAlbumCovers();
  }, [playlist, token, searchTrackURI, getTrackDetails]);

  const handleExportToSpotify = async () => {
    if (!enhancedPlaylist.length) {
      alert("No songs to export!");
      return;
    }

    setIsExporting(true);
    setExportProgress(0);

    try {
      const trackURIs: string[] = [];

      for (let i = 0; i < enhancedPlaylist.length; i++) {
        const song = enhancedPlaylist[i];

        if (song.uri) {
          trackURIs.push(song.uri);
        }

        setExportProgress(
          Math.round(((i + 1) / enhancedPlaylist.length) * 100)
        );
      }

      if (trackURIs.length === 0) {
        alert("No Spotify tracks found to export!");
        return;
      }

      // Create playlist with cover image
      const description = coverImage
        ? "Generated by YouLists AI from your image"
        : "Generated by YouLists AI";

      const playlistLink = await createSpotifyPlaylist(
        customPlaylistName,
        trackURIs,
        description,
        coverImage
      );

      setExportedPlaylistURL(playlistLink);
    } catch (error) {
      console.error("Error exporting to Spotify:", error);
      alert("Failed to export playlist to Spotify. Please try again.");
    } finally {
      setIsExporting(false);
    }
  };

  const handleSaveToHistory = () => {
    savePlaylist(customPlaylistName, enhancedPlaylist);
    setSavedToHistory(true);

    setTimeout(() => {
      setSavedToHistory(false);
    }, 3000);
  };

  const handleRegenerate = () => {
    navigate("/loading", {
      state: {
        prompt: lastPrompt,
        songCount,
        advancedParameters,
        selectedImage,
      },
    });
  };

  const getDurationEstimate = useCallback(() => {
    if (enhancedPlaylist.length === 0) return "";
    const totalMs = enhancedPlaylist.reduce((acc, t) => acc + (t.duration_ms || 210000), 0);
    const totalMin = Math.round(totalMs / 60000);
    return `~${totalMin} min`;
  }, [enhancedPlaylist]);

  const handleShareAsImage = async () => {
    const canvas = document.createElement("canvas");
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    const w = 600;
    const h = 800;
    canvas.width = w;
    canvas.height = h;

    ctx.fillStyle = "#1a1a1a";
    ctx.fillRect(0, 0, w, h);

    ctx.fillStyle = "#3E7C59";
    const barHeights = [26, 40, 52, 36, 46];
    const barW = 6;
    const barGap = 4;
    const iconX = (w - (barW * 5 + barGap * 4)) / 2;
    const iconY = 40;
    barHeights.forEach((bh, i) => {
      const x = iconX + i * (barW + barGap);
      const y = iconY + (52 - bh);
      ctx.beginPath();
      ctx.roundRect(x, y, barW, bh, 3);
      ctx.fill();
    });

    ctx.font = "500 24px 'Noto Sans Mono', monospace";
    ctx.textAlign = "center";
    ctx.fillStyle = "#ffffff";
    const wordY = iconY + 52 + 30;
    const youWidth = ctx.measureText("you").width;
    const listsWidth = ctx.measureText("lists").width;
    const totalWidth = youWidth + listsWidth;
    ctx.fillText("you", w / 2 - totalWidth / 2 + youWidth / 2, wordY);
    ctx.fillStyle = "#3E7C59";
    ctx.fillText("lists", w / 2 + totalWidth / 2 - listsWidth / 2, wordY);

    ctx.font = "500 20px 'Noto Sans Mono', monospace";
    ctx.fillStyle = "#ffffff";
    ctx.textAlign = "center";
    const name = customPlaylistName.length > 30 ? customPlaylistName.substring(0, 30) + "..." : customPlaylistName;
    ctx.fillText(name, w / 2, wordY + 50);

    if (tags.length > 0) {
      ctx.font = "400 11px 'Noto Sans Mono', monospace";
      ctx.fillStyle = "#3E7C59";
      ctx.fillText(tags.join(" / "), w / 2, wordY + 75);
    }

    const tracksToShow = enhancedPlaylist.slice(0, 10);
    ctx.textAlign = "left";
    const startY = wordY + 110;
    tracksToShow.forEach((track, i) => {
      const y = startY + i * 40;
      ctx.font = "400 12px 'Noto Sans Mono', monospace";
      ctx.fillStyle = "#888888";
      ctx.fillText(`${(i + 1).toString().padStart(2, "0")}`, 60, y);
      ctx.font = "500 13px 'Noto Sans Mono', monospace";
      ctx.fillStyle = "#ffffff";
      const title = track.title.length > 28 ? track.title.substring(0, 28) + "..." : track.title;
      ctx.fillText(title, 90, y);
      ctx.font = "400 11px 'Noto Sans Mono', monospace";
      ctx.fillStyle = "#888888";
      const artist = track.artist.length > 30 ? track.artist.substring(0, 30) + "..." : track.artist;
      ctx.fillText(artist, 90, y + 16);
    });

    ctx.font = "400 10px 'Noto Sans Mono', monospace";
    ctx.fillStyle = "#888888";
    ctx.textAlign = "center";
    ctx.fillText("made with youlists", w / 2, h - 30);

    canvas.toBlob((blob) => {
      if (!blob) return;
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${customPlaylistName.replace(/[^a-z0-9]/gi, "_")}.png`;
      a.click();
      URL.revokeObjectURL(url);
    }, "image/png");
  };

  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.metaKey || e.ctrlKey) {
        if (e.key === "s") {
          e.preventDefault();
          handleSaveToHistory();
        } else if (e.key === "e" && !isGuestMode) {
          e.preventDefault();
          handleExportToSpotify();
        }
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [enhancedPlaylist, customPlaylistName]);

  const openSpotifySearch = (song: EnhancedSong) => {
    const query = `${song.title} ${song.artist}`;
    window.open(
      `https://open.spotify.com/search/${encodeURIComponent(query)}`,
      "_blank"
    );
  };

  return (
    <div className="page">
      <header className="header">
        <button className="back-btn" onClick={() => navigate("/home")}>
          <ArrowLeft size={18} />
          back
        </button>

        <div className="header-actions">
          <button className="icon-btn" onClick={toggleTheme}>
            {theme === "light" ? <Moon size={18} /> : <Sun size={18} />}
          </button>

          <button
            className="icon-btn"
            onClick={handleSaveToHistory}
            style={{
              background: savedToHistory ? "var(--accent-primary)" : undefined,
              color: savedToHistory ? "white" : undefined,
            }}
          >
            <Save size={18} />
          </button>

          <button className="icon-btn" onClick={handleShareAsImage} title="share as image">
            <Download size={18} />
          </button>
        </div>
      </header>

      <main className="main playlist-main">
        <div className="playlist-header">
          {/* Show small cover image indicator if available */}
          {coverImage && (
            <div className="playlist-cover-indicator">
              <img
                src={coverImage.dataUrl}
                alt="Playlist cover"
                className="cover-indicator-image"
              />
              <span className="cover-indicator-text">
                cover image ready for spotify
              </span>
            </div>
          )}

          <div style={{ display: "flex", alignItems: "center", gap: "8px" }}>
            <input
              type="text"
              value={customPlaylistName}
              onChange={(e) => setCustomPlaylistName(e.target.value)}
              className="playlist-name-input"
              placeholder="playlist name..."
              style={{ marginBottom: 0 }}
            />
            <button
              className="icon-btn"
              onClick={handleRegenerate}
              title="regenerate"
              style={{ flexShrink: 0 }}
            >
              <RefreshCw size={16} />
            </button>
          </div>
          <p className="playlist-info">
            {enhancedPlaylist.length} tracks / {getDurationEstimate()}
            {isEnhancing && " • loading album covers..."}
            {coverImage && " • cover image ready"}
          </p>

          {tags.length > 0 && (
            <div className="playlist-tags">
              {tags.map((tag) => (
                <span key={tag} className="playlist-tag">{tag}</span>
              ))}
            </div>
          )}
        </div>

        {enhancedPlaylist.length > 0 ? (
          <div className="playlist-tracks">
            {enhancedPlaylist.map((track: EnhancedSong, index: number) => (
              <div
                key={`${track.title}-${track.artist}-${index}`}
                className="track-item"
              >
                <span className="track-number">{index + 1}</span>

                <div className="track-cover">
                  {track.coverUrl ? (
                    <img
                      src={track.coverUrl}
                      alt={`${track.title} album cover`}
                      className="album-cover"
                      loading="lazy"
                    />
                  ) : (
                    <div className="album-cover-placeholder">
                      <svg
                        width="20"
                        height="20"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        strokeWidth="2"
                      >
                        <path d="M9 18V5l12-2v13"></path>
                        <circle cx="6" cy="18" r="3"></circle>
                        <circle cx="18" cy="16" r="3"></circle>
                      </svg>
                    </div>
                  )}
                </div>

                <div className="track-info">
                  <div className="track-title">{track.title}</div>
                  <div className="track-artist">{track.artist}</div>
                </div>

                <button
                  className="track-action"
                  onClick={() => openSpotifySearch(track)}
                >
                  <ExternalLink size={16} />
                </button>
              </div>
            ))}
          </div>
        ) : (
          <div
            style={{
              textAlign: "center",
              padding: "40px 0",
              color: "var(--text-secondary)",
            }}
          >
            <p>No tracks found. Try generating a new playlist.</p>
          </div>
        )}

        <div className="export-section">
          {isGuestMode ? (
            <UniversalExport
              playlist={enhancedPlaylist}
              playlistName={customPlaylistName}
            />
          ) : (
            <>
              {!exportedPlaylistURL ? (
                <>
                  {isExporting ? (
                    <div style={{ marginBottom: "20px" }}>
                      <div className="progress-bar">
                        <div
                          className="progress-fill"
                          style={{ width: `${exportProgress}%` }}
                        />
                      </div>
                      <p
                        style={{
                          fontSize: "12px",
                          color: "var(--text-secondary)",
                          marginTop: "8px",
                        }}
                      >
                        {exportProgress < 100
                          ? `searching for tracks... ${exportProgress}%`
                          : coverImage
                          ? "uploading cover image..."
                          : "finalizing playlist..."}
                      </p>
                    </div>
                  ) : (
                    <button
                      className="export-btn"
                      onClick={handleExportToSpotify}
                      disabled={enhancedPlaylist.length === 0}
                    >
                      export to spotify
                      {coverImage && " with cover"}
                    </button>
                  )}
                </>
              ) : (
                <div style={{ textAlign: "center" }}>
                  <p
                    style={{
                      color: "var(--accent-primary)",
                      marginBottom: "16px",
                      fontSize: "14px",
                    }}
                  >
                    ✓ successfully exported to spotify!
                    {coverImage && " cover image included."}
                  </p>
                  <a
                    href={exportedPlaylistURL}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="export-btn"
                    style={{ textDecoration: "none", display: "inline-block" }}
                  >
                    open in spotify
                  </a>
                </div>
              )}
            </>
          )}
        </div>
      </main>
    </div>
  );
};

export default PlaylistPage;
